import { describe, expect, it } from "vitest";

import {
  macBundleVersionFromSemver,
  macMarketingVersionFromSemver,
  updateCargoLockPackageVersion,
  updateWindowsResourceFlags,
  updateWindowsResourceVersion,
  updateWindowsShellResourceDestinations,
  windowsPackageVersionFromSemver,
} from "../../scripts/sync-version-helpers.js";

const resource = `#ifdef _DEBUG
 FILEFLAGS VS_FF_DEBUG | VS_FF_PRERELEASE
#else
 FILEFLAGS VS_FF_PRERELEASE
#endif`;

describe("Cargo.lock package version", () => {
  const lockfile = `# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "anyhow"
version = "1.0.0"

[[package]]
name = "zinnia"
version = "0.6.0-beta.10"
dependencies = [
 "anyhow",
]
`;

  it("updates only the named package version", () => {
    expect(updateCargoLockPackageVersion(lockfile, "zinnia", "0.6.0-beta.11"))
      .toBe(`# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "anyhow"
version = "1.0.0"

[[package]]
name = "zinnia"
version = "0.6.0-beta.11"
dependencies = [
 "anyhow",
]
`);
  });

  it("fails when the package entry is missing", () => {
    expect(() =>
      updateCargoLockPackageVersion(lockfile, "missing", "1.0.0"),
    ).toThrow(/missing \[\[package\]\]/);
  });
});

describe("Windows resource version flags", () => {
  it("marks beta builds as prerelease", () => {
    expect(updateWindowsResourceFlags(resource, "0.6.0-beta.4")).toBe(resource);
  });

  it("removes prerelease flags from stable builds", () => {
    expect(updateWindowsResourceFlags(resource, "0.6.0")).toBe(`#ifdef _DEBUG
 FILEFLAGS VS_FF_DEBUG
#else
 FILEFLAGS 0
#endif`);
  });

  it("fails if the expected resource block is missing", () => {
    expect(() => updateWindowsResourceFlags("FILEFLAGS 0", "0.6.0")).toThrow(
      /FILEFLAGS block was not found/,
    );
  });
});

describe("Windows resource version fields", () => {
  const fullResource = ` FILEVERSION 0,5,0,1
 PRODUCTVERSION 0,5,0,1
${resource}
      VALUE "FileVersion", "0.5.0\\0"
      VALUE "ProductVersion", "0.5.0\\0"`;

  it("updates every required numeric and string version field", () => {
    const updated = updateWindowsResourceVersion(fullResource, "0.6.0");
    expect(updated).toContain(" FILEVERSION 0,6,0,65535");
    expect(updated).toContain(" PRODUCTVERSION 0,6,0,65535");
    expect(updated).toContain('VALUE "FileVersion", "0.6.0\\0"');
    expect(updated).toContain('VALUE "ProductVersion", "0.6.0\\0"');
  });

  it("fails if any expected RC version replacement is missing", () => {
    expect(() =>
      updateWindowsResourceVersion(
        fullResource.replace(/^ PRODUCTVERSION .+\n/m, ""),
        "0.6.0",
      ),
    ).toThrow(/PRODUCTVERSION.*exactly once/);
  });
});

describe("Windows package version", () => {
  it("keeps beta, stable, and the next patch monotonically ordered", () => {
    const versions = [
      "0.6.0-beta.1",
      "0.6.0-beta.14",
      "0.6.0",
      "0.6.1-beta.0",
    ].map(windowsPackageVersionFromSemver);

    expect(versions).toEqual(["0.6.0.1", "0.6.0.14", "0.6.0.65535", "0.6.1.0"]);
    for (let index = 1; index < versions.length; index += 1) {
      const previous = versions[index - 1].split(".").map(Number);
      const current = versions[index].split(".").map(Number);
      const differingIndex = current.findIndex(
        (part, partIndex) => part !== previous[partIndex],
      );
      expect(differingIndex).toBeGreaterThanOrEqual(0);
      expect(current[differingIndex]).toBeGreaterThan(previous[differingIndex]);
    }
  });

  it("rejects unsupported prerelease forms and out-of-range components", () => {
    expect(() => windowsPackageVersionFromSemver("0.6.0-preview.1")).toThrow(
      /cannot be represented/,
    );
    expect(() => windowsPackageVersionFromSemver("0.6.0-alpha.1")).toThrow(
      /cannot be represented/,
    );
    expect(() => windowsPackageVersionFromSemver("0.6.0-rc.1")).toThrow(
      /cannot be represented/,
    );
    expect(() => windowsPackageVersionFromSemver("0.6.0-beta.014")).toThrow(
      /cannot be represented/,
    );
    expect(() => windowsPackageVersionFromSemver("0.6.0-beta.65535")).toThrow(
      /0-65534/,
    );
    expect(() => windowsPackageVersionFromSemver("65536.0.0")).toThrow(
      /exceeds 65535/,
    );
  });
});

describe("Windows shell resource destinations", () => {
  it("writes every shell artifact to the concrete release directory", () => {
    const resources = {
      "windows/shell/out/zinnia_shell.dll": "old/zinnia_shell.dll",
      "windows/shell/out/zinnia_extract_shell.dll":
        "old/zinnia_extract_shell.dll",
      "windows/shell/out/ZinniaContextMenu.msix": "old/ZinniaContextMenu.msix",
      "windows/shell/out/ZinniaExtractContextMenu.msix":
        "old/ZinniaExtractContextMenu.msix",
      "../scripts/register-windows-context-menu.ps1":
        "old/register-windows-context-menu.ps1",
      "unrelated.txt": "keep/unrelated.txt",
    };
    const config = { bundle: { resources } };

    const updated = updateWindowsShellResourceDestinations(
      config,
      "0.6.0-beta.14",
    );

    expect(updated.bundle.resources).toEqual({
      "windows/shell/out/zinnia_shell.dll":
        "shell-0.6.0-beta.14/zinnia_shell.dll",
      "windows/shell/out/zinnia_extract_shell.dll":
        "shell-0.6.0-beta.14/zinnia_extract_shell.dll",
      "windows/shell/out/ZinniaContextMenu.msix":
        "shell-0.6.0-beta.14/ZinniaContextMenu.msix",
      "windows/shell/out/ZinniaExtractContextMenu.msix":
        "shell-0.6.0-beta.14/ZinniaExtractContextMenu.msix",
      "../scripts/register-windows-context-menu.ps1":
        "shell-0.6.0-beta.14/register-windows-context-menu.ps1",
      "unrelated.txt": "keep/unrelated.txt",
    });
    expect(config.bundle.resources).toBe(resources);
  });

  it("fails when a required shell artifact is removed from packaging", () => {
    expect(() =>
      updateWindowsShellResourceDestinations(
        { bundle: { resources: {} } },
        "0.6.0-beta.14",
      ),
    ).toThrow(/missing shell resource/);
  });
});

describe("macOS bundle version", () => {
  it("converts prerelease and stable SemVer versions into ordered numeric builds", () => {
    expect(macBundleVersionFromSemver("0.6.0-beta.4")).toBe("0.6.34");
    expect(macBundleVersionFromSemver("0.6.0")).toBe("0.6.99");
    expect(macBundleVersionFromSemver("0.6.1-beta.1")).toBe("0.6.131");
  });

  it("rejects unsupported prerelease version forms", () => {
    expect(() => macBundleVersionFromSemver("0.6.0-preview.1")).toThrow(
      /cannot be represented/,
    );
    expect(() => macBundleVersionFromSemver("0.6.0-alpha.1")).toThrow(
      /cannot be represented/,
    );
    expect(() => macBundleVersionFromSemver("0.6.0-rc.1")).toThrow(
      /cannot be represented/,
    );
    expect(() => macBundleVersionFromSemver("0.6.0-beta.04")).toThrow(
      /cannot be represented/,
    );
    expect(() => macBundleVersionFromSemver("0.6.0-beta.30")).toThrow(/0-29/);
  });
});

describe("macOS marketing version", () => {
  it("uses the numeric SemVer core for stable and prerelease builds", () => {
    expect(macMarketingVersionFromSemver("0.6.0-beta.13")).toBe("0.6.0");
    expect(macMarketingVersionFromSemver("1.2.3")).toBe("1.2.3");
  });

  it("rejects unsupported version forms", () => {
    expect(() => macMarketingVersionFromSemver("1.2")).toThrow(
      /cannot be represented/,
    );
    expect(() => macMarketingVersionFromSemver("1.2.3-preview.1")).toThrow(
      /cannot be represented/,
    );
  });
});
