import fs from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";

function readCapability(name: "default" | "extract" | "debug-console"): {
  permissions: string[];
} {
  const file = path.resolve(
    process.cwd(),
    "src-tauri",
    "capabilities",
    `${name}.json`,
  );
  return JSON.parse(fs.readFileSync(file, "utf8"));
}

describe("Tauri capability policy", () => {
  it("keeps generated command permissions aligned with the Rust manifest and handler", () => {
    const buildRs = fs.readFileSync(
      path.resolve(process.cwd(), "src-tauri", "build.rs"),
      "utf8",
    );
    const mainRs = fs.readFileSync(
      path.resolve(process.cwd(), "src-tauri", "src", "main.rs"),
      "utf8",
    );
    const manifestMatch = buildRs.match(
      /const COMMANDS: &\[&str\] = &\[([\s\S]*?)\];/,
    );
    const handlerMatch = mainRs.match(/generate_handler!\[([\s\S]*?)\]\)/);
    expect(manifestMatch?.[1]).toBeDefined();
    expect(handlerMatch?.[1]).toBeDefined();

    const manifestCommands = [
      ...(manifestMatch?.[1].matchAll(/"([^"]+)"/g) ?? []),
    ].map((match) => match[1]);
    const handlerCommands = [
      ...(handlerMatch?.[1].matchAll(/::(\w+),?/g) ?? []),
    ].map((match) => match[1]);
    const generatedPermissions = new Set(
      fs
        .readdirSync(
          path.resolve(
            process.cwd(),
            "src-tauri",
            "permissions",
            "autogenerated",
          ),
        )
        .map((file) => path.basename(file, ".toml")),
    );

    expect(new Set(manifestCommands)).toEqual(new Set(handlerCommands));
    for (const command of handlerCommands) {
      expect(generatedPermissions).toContain(command);
    }
  });

  it("grants only the dialog, updater, process, notification, and shell APIs Zinnia uses", () => {
    const { permissions } = readCapability("default");

    expect(permissions).toEqual(
      expect.arrayContaining([
        "dialog:allow-message",
        "dialog:allow-open",
        "dialog:allow-save",
        "shell:default",
        "updater:allow-check",
        "updater:allow-download",
        "updater:allow-install",
        "process:allow-restart",
        "notification:allow-is-permission-granted",
        "notification:allow-request-permission",
        "notification:allow-notify",
      ]),
    );
    expect(permissions).not.toEqual(
      expect.arrayContaining([
        "dialog:default",
        "updater:default",
        "process:default",
        "notification:default",
        "shell:allow-execute",
        "shell:allow-spawn",
      ]),
    );
    expect(permissions).toEqual(
      expect.arrayContaining([
        "core:app:allow-version",
        "core:event:allow-listen",
        "core:event:allow-unlisten",
      ]),
    );
    expect(permissions).not.toContain("core:default");
  });

  it("keeps generated capabilities.json permissions aligned with default.json", () => {
    const { permissions } = readCapability("default");
    const generated = JSON.parse(
      fs.readFileSync(
        path.resolve(
          process.cwd(),
          "src-tauri",
          "gen",
          "schemas",
          "capabilities.json",
        ),
        "utf8",
      ),
    ) as { default?: { permissions?: string[] } };
    expect(new Set(generated.default?.permissions ?? [])).toEqual(
      new Set(permissions),
    );
    expect(generated.default?.permissions).toContain("shell:default");
  });

  it("grants every invoke used by extract-window.ts", () => {
    const source = fs.readFileSync(
      path.resolve(process.cwd(), "src", "extract-window.ts"),
      "utf8",
    );
    const commands = [
      ...source.matchAll(/invoke(?:<[^>]+>)?\(\s*["'](\w+)["']/g),
    ].map((match) => match[1]);
    expect(commands.length).toBeGreaterThan(0);

    const { permissions } = readCapability("extract");
    const granted = new Set(permissions);
    for (const command of new Set(commands)) {
      const allow = `allow-${command.replaceAll("_", "-")}`;
      expect(granted, `extract window invokes ${command}`).toContain(allow);
    }
  });

  it("keeps extract windows to their explicit core APIs", () => {
    const { permissions } = readCapability("extract");

    expect(permissions).toEqual(
      expect.arrayContaining([
        "core:event:allow-listen",
        "core:event:allow-unlisten",
        "core:window:allow-close",
        "core:window:allow-minimize",
        "core:window:allow-start-dragging",
        "allow-probe-7z",
        "allow-load-settings",
        "allow-set-workspace-window-fx",
        "allow-supports-workspace-window-fx",
      ]),
    );
    expect(permissions).not.toContain("core:default");
  });

  it("keeps the debug console window to listen plus an allowlisted signal relay", () => {
    const source = fs.readFileSync(
      path.resolve(process.cwd(), "src", "debug-console-window.ts"),
      "utf8",
    );
    const commands = [
      ...source.matchAll(/invoke(?:<[^>]+>)?\(\s*["'](\w+)["']/g),
    ].map((match) => match[1]);
    expect(commands).toContain("relay_debug_console_signal");

    const { permissions } = readCapability("debug-console");
    const granted = new Set(permissions);
    for (const command of new Set(commands)) {
      const allow = `allow-${command.replaceAll("_", "-")}`;
      expect(granted, `debug console invokes ${command}`).toContain(allow);
    }
    expect(permissions).toContain("allow-relay-debug-console-signal");
    expect(permissions).not.toContain("core:event:allow-emit");
    expect(permissions).not.toContain("allow-run-7z");
    expect(permissions).not.toContain("allow-open-path");
    expect(permissions).not.toContain("updater:allow-check");
  });
});
