import fs from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";

function readCapability(name: "default" | "extract"): {
  permissions: string[];
} {
  const file = path.resolve(
    process.cwd(),
    "src-tauri",
    "capabilities",
    `${name}.json`,
  );
  return JSON.parse(fs.readFileSync(file, "utf8"));
}

describe("Tauri capability policy", () => {
  it("keeps generated command permissions aligned with the Rust manifest and handler", () => {
    const buildRs = fs.readFileSync(
      path.resolve(process.cwd(), "src-tauri", "build.rs"),
      "utf8",
    );
    const mainRs = fs.readFileSync(
      path.resolve(process.cwd(), "src-tauri", "src", "main.rs"),
      "utf8",
    );
    const manifestMatch = buildRs.match(
      /const COMMANDS: &\[&str\] = &\[([\s\S]*?)\];/,
    );
    const handlerMatch = mainRs.match(/generate_handler!\[([\s\S]*?)\]\)/);
    expect(manifestMatch?.[1]).toBeDefined();
    expect(handlerMatch?.[1]).toBeDefined();

    const manifestCommands = [
      ...(manifestMatch?.[1].matchAll(/"([^"]+)"/g) ?? []),
    ].map((match) => match[1]);
    const handlerCommands = [
      ...(handlerMatch?.[1].matchAll(/::(\w+),?/g) ?? []),
    ].map((match) => match[1]);
    const generatedPermissions = new Set(
      fs
        .readdirSync(
          path.resolve(
            process.cwd(),
            "src-tauri",
            "permissions",
            "autogenerated",
          ),
        )
        .map((file) => path.basename(file, ".toml")),
    );

    expect(new Set(manifestCommands)).toEqual(new Set(handlerCommands));
    for (const command of handlerCommands) {
      expect(generatedPermissions).toContain(command);
    }
  });

  it("grants only the dialog, updater, process, and notification APIs Zinnia uses", () => {
    const { permissions } = readCapability("default");

    expect(permissions).toEqual(
      expect.arrayContaining([
        "dialog:allow-message",
        "dialog:allow-open",
        "dialog:allow-save",
        "updater:allow-check",
        "updater:allow-download",
        "updater:allow-install",
        "process:allow-restart",
        "notification:allow-is-permission-granted",
        "notification:allow-request-permission",
        "notification:allow-notify",
      ]),
    );
    expect(permissions).not.toEqual(
      expect.arrayContaining([
        "dialog:default",
        "updater:default",
        "process:default",
        "notification:default",
      ]),
    );
    expect(permissions).toEqual(
      expect.arrayContaining([
        "core:app:allow-version",
        "core:event:allow-listen",
        "core:event:allow-unlisten",
      ]),
    );
    expect(permissions).not.toContain("core:default");
  });

  it("keeps extract windows to their explicit core APIs", () => {
    const { permissions } = readCapability("extract");

    expect(permissions).toEqual(
      expect.arrayContaining([
        "core:event:allow-listen",
        "core:event:allow-unlisten",
        "core:window:allow-close",
        "core:window:allow-minimize",
        "core:window:allow-start-dragging",
      ]),
    );
    expect(permissions).not.toContain("core:default");
  });
});
